### ISSUE TITLE
Projects in the Repo Are Annotated w/ a Warning "Has no explicit encoding set".

### ISSUE THREAD

**Issue by ingomohr** [eclipse-platform/eclipse.platform.resources#168]
Dear all,

while working on my issue #166 I realized that the projects in this repo themselves cause the warning marker "has no explicit encoding set". 
Shouldn't the projects whose code introduced that marker to be added in the first place be the first projects to be migrated? ;)

![image](https://user-images.githubusercontent.com/2838592/179234843-1043b079-1fc4-4b6f-8975-92ddbd7593da.png)

**Comment by iloveeclipse** [comment]
Feel free to provide a patch...

**Comment by ingomohr** [comment]
> Feel free to provide a patch...

I'll do that.

**Comment by ingomohr** [comment]
I created PR #175 for the change. (used only the quickfix to make the change)

**Comment by akurtakov** [comment]
Thanks for the contribution, merged now.
