### ISSUE TITLE
Compiler markers in text editor not updated

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.resources#17]
In Eclipse SDK
Version: 2022-06 (4.24)
Build id: I20220324-1800
OS: Linux, v.5.13.0-37-generic, x86_64 / gtk 3.24.30, WebKit 2.34.6
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.1+12
Java version: 17.0.1

the error markers in the text editor are not updated automatically. I have to clean the project to update the editor. Maybe a follow-up issue of https://git.eclipse.org/r/c/platform/eclipse.platform.resources/+/190487?

Example:

Implement an interface, delete the interface, wait for compiler to show errors, use Staging view to restore file -> errors still in the editor

![image](https://user-images.githubusercontent.com/139910/160619942-6ab14211-9bb6-4bad-8718-61a2f261cd88.png)

**Comment by vogella** [comment]
cc @jukzi

**Comment by iloveeclipse** [comment]
I can't reproduce with I20220328-1800 build. Note, there were few patches already merged to fix various issues, so might be that was fixed in the meanwhile.

**Comment by vogella** [comment]
I20220328-1800 does not open on Linux for me, complains that JDT classes cannot be found. I try with tomorrows build again and will reopen if the issue still exists.

**Comment by iloveeclipse** [comment]
> I20220328-1800 does not open on Linux for me, complains that JDT classes cannot be found.
Fresh install or update? I'm using fresh one, no problems. What exactly is reported by whom?

**Comment by merks** [comment]
I saw a bug about notifications related to marker changes that were caused by changes to the marker map implementation.  That was fixed I think so maybe you caught the tail end of that.

**Comment by vogella** [comment]
Today all seems good with Eclipse SDK
Version: 2022-06 (4.24)
Build id: I20220329-1800
OS: Linux, v.5.13.0-37-generic, x86_64 / gtk 3.24.30
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.1+12
Java version: 17.0.1
