### ISSUE TITLE
Finalize the merge of this repository

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.resources#182]
This repo now needs the same treatment as this one:

https://github.com/eclipse-platform/eclipse.platform.team

Also this should stop listing those repos, right?

https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md

I think a bunch of the repos listed there are merged and should be removed....

**Comment by akurtakov** [comment]
Yes and yes.

**Comment by merks** [comment]
@iloveeclipse @laeubi 

I'm not sure how the other repos were "closed"..

**Comment by iloveeclipse** [comment]
It wasn't me,  so no idea

**Comment by vogella** [comment]
> @iloveeclipse @laeubi
> 
> I'm not sure how the other repos were "closed"..

* Remove everything from master except a Readme which explains the new home
* Transfer all issues 
*  close all PRs with a comment to recreate them to the new location

**Comment by akurtakov** [comment]
I think this is done now.
