### ISSUE TITLE
Make github build action similar to Jenkins one

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.resources#25]
See https://github.com/eclipse-platform/eclipse.platform.resources/commit/b0c0ef081b176cebbec46682eaa28a233b6657ab#r70012850

Ideally we should do exact same build kind as Jenkins / have same result.

**Comment by iloveeclipse** [comment]
@vogella : I see you have tests enabled in last PR for github action. Was this on purpose? Shouldn't it be *only build* validation?

**Comment by vogella** [comment]
> @vogella : I see you have tests enabled in last PR for github action. Was this on purpose? Shouldn't it be _only build_ validation?

See title of the Github issue: https://github.com/eclipse-platform/eclipse.platform.resources/issues/23
