### ISSUE TITLE
Unable to push to the forked repo

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.resources#26]
I get this error now trying to push a branch to my forked github repo:
```
Repository https://github.com/iloveeclipse/eclipse.platform.resources

refusing to allow a Personal Access Token to create or update workflow `.github/workflows/maven.yml` without `workflow` scope
```
This seem to happen after #18 (or one of the following changes).

Looks like everyone now has to regenerate the PA token?
https://stackoverflow.com/questions/68811838/refusing-to-allow-a-personal-access-token-to-create-or-update-workflow

Direct link is https://github.com/settings/tokens

**Comment by vogella** [comment]
>  regenerate the PA token?

Only if you did not include the workflow permission into your token. Alternative you can use an SSH key for access.
