### ISSUE TITLE
Add option to delete a resource without additional check

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.resources#31]
If I delete via Eclipse I also get the confirmation dialog, while Code offers me the option to not ask again. I would love to see this also in Eclipse.

![image](https://user-images.githubusercontent.com/139910/161217351-0ba59c60-f409-404a-9809-ae821ce22fe4.png)

IIRC the functionality span platform and JDT so I hope @jukzi who works in both worlds would be interested in implementing this. If not I most likely will close this issue in a while, no need to have features request lying around.

**Comment by mickaelistria** [comment]
This is to be reported to eclipse.platform.ui which provides the dialog and the DeleteOperation. The resource model API doesn't mandate anything of that sort.

**Comment by jukzi** [comment]
At the moment i do not even get my own changes reviewed @ jdt. so no: i can't do.

**Comment by vogella** [comment]
Ok lets close this for now.
