### ISSUE TITLE
Remove "old" workspace support

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.resources#92]
While reviewing https://github.com/eclipse-platform/eclipse.platform.resources/pull/87 I've stumbled over very old code in org.eclipse.core.internal.resources.WorkspaceDescriptionReader that was committed 2003 and seem to be there to support old (pre-2.1?) workspaces. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=32235

I assume we don't need to keep that compatibility anymore, because migrating 2.0 workspaces to 4.x is probably nothing we want support.

**Comment by vogella** [comment]
Thanks!
